server {
    listen     80;
    server_name _;
    root /var/www/;
    index index.html ;

    location / {
        index  index.html index.php;
        if (!-e $request_filename) {
           rewrite ^/(.*)$ /index.html last;
        }
    }

    location ~ /attached/image {
       rewrite ^/attached/image(.*) https://www.duomai.com/attached/image$1 permanent;
       break;
    }
    gzip on;
    gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png application/vnd.ms-fontobject font/ttf font/opentype font/x-woff image/svg+xml;
    location ~* \.(html)$ {
        add_header Cache-Control "no-store";
    }

    location ~* ^.+.(swf|jpg|jpeg|gif|css|png|js|ico)$ {
        access_log        off;
        expires           180s;
        #expires           -1s;
        #add_header Cache-Control no-store;
    }

    location = /robots.txt  { access_log off; log_not_found off; }
    location = /favicon.ico { access_log off; log_not_found off; expires 30d; }
    location ~ /\.          { access_log off; log_not_found off; deny all; }
    location ~ ~$           { access_log off; log_not_found off; deny all; }

    location ~ /\.ht {
        deny  all;
    }
}